<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <div class="field">
        <div class="input-box">
            <select name="payment[opay_choosen_payment]" class="validate-select validation-passed" title="OpayPayment">
                <?php
                    $opayPaymentMethods = $this->getMethod()->getConfigData('opay_payment_methods');
                    $list = explode(',', $opayPaymentMethods);
                    foreach ($list as $payment) {
                        echo '<option value="' . $payment . '">' . $this->__('opay_payment_text_' . $payment) . '</option>';
                    }
                ?>
            </select>
        </div>
    </div>
</div>